### ISSUE TITLE
Translation "he"

### ISSUE THREAD

**Issue by sjehuda** [deltachat/deltachat-pages#1097]
```yaml
he:
  
  meta:
    description: Delta Chat - מסרים מידיים מבוססי דוא״ל
    keywords: delta chat, email messaging app, download delta chat
    rss_news_title: חדשות Delta Chat

  menu:
    home: בית
    download: הורדה
    blog: כתב עת
    contribute: סייעו
    help: שו״ת
    forum: פורום

  subscribe_to_feed: הרשמה להזנה שלנו

  references: הפניות
  donate: תרמו
  imprint: חותם
  privacy: מדיניות פרטיות
  language: שפה

  download:
    other: אפשרויות הורדה לפלטפורמות אחרות
    no_upgrades: אפשרויות הורדה בלי עדכונים אוטומטיים
    source_code: קוד מקור
    outdated: מיושן
    minimum: דרישות מינימליות
    dl_flathub: הורדה מחנות Flathub
    dl_microsoft: הורדה מחנות Microsoft
    dl_mac_appstore: הורדה מחנות Apple Mac AppStore
    dl_appstore: הורדה מחנות Apple AppStore
    dl_fdroid: הורדה מחנות F-Droid
    gplay: הורדה מחנות Google Play

  help:
    offline_hint: אתם ממהרים? אתם יכולים לקרוא את מדריך עזרה זה בנינוחות בכל עת מתוך האפליקציה, אפילו בלי אינטרנט.
```

Is there a translation template for the site WebXDC also?
